services:
  apps-fe-dev:
    image: apps-fe-dev:latest
    build: .
    container_name: apps-fe-dev
    restart: always
    ports:
      - "1100:80"
    networks:
      - web-profile-net

networks:
  web-profile-net:
    driver: bridge
